name: modular-vsa

services:
  postgres:
    image: postgres
    container_name: modular-vsa-postgres
    environment:
      POSTGRES_DB: modular-vsa
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"
    volumes:
      - modular-vsa_postgres_data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  modular-vsa_postgres_data:
